export const OBJECT_INPUT_CHANGED = 'OBJECT_INPUT_CHANGED';

export const OBJECT_CHECKBOX_CHANGED = 'OBJECT_CHECKBOX_CHANGED';

export const OBJECT_RANGE_CHANGED = 'OBJECT_RANGE_CHANGED';

export const OBJECT_TEXTAREA_CHANGED = 'OBJECT_TEXTAREA_CHANGED';

export const OBJECT_RADIOBUTTON_CHANGED = 'OBJECT_RADIOBUTTON_CHANGED';


